# Project information
site_name: OnTime.JS JSON Format
site_description: 'Specification of the OnTime.JS JSON Format'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.ontimejs-json.stueber.co.uk'

# Copyright
copyright: © 2020 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'On GitHub'
repo_url: 'https://github.com/stuebersystems/doc.ontimejs-json'

# Theming
# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    feature:
        - tabs
        - instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Imprint
      link: https://www.stueber.co.uk/imprint.php
    - label: Privacy
      link: https://legal.stueber.co.uk/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Introduction: index.md
- Objects:
  - onplan: objects/onplan.md
  - result: objects/result.md
  - about: objects/about.md
  - note: objects/note.md
  - user: objects/user.md
  - users: objects/users.md
  - Schedule objects: 
    - classAbsence: objects/classAbsence.md
    - roomAbsence: objects/roomAbsence.md
    - teacherAbsence: objects/teacherAbsence.md
    - displaySchedule: objects/displaySchedule.md
  - Catalogue objects:
    - area: objects/area.md
    - building: objects/building.md
    - candidate: objects/candidate.md
    - catalogEntry: objects/catalogEntry.md
    - class: objects/class.md
    - course: objects/course.md
    - resource: objects/resource.md
    - room: objects/room.md
    - student: objects/student.md
    - subject: objects/subject.md
    - teacher: objects/teacher.md
    - team: objects/team.md
    - timeframe: objects/timeframe.md